myLogger_Enum
vpopova294/AutoQALP pull request #4
Opened 2022-07-07 19:23 UTC by vpopova294

у меня есть проблемы с добавлением логгера в существующий класс, в строке 18 
пыталась сделать LOGGER.log(Level.ERROR, "show log error"); но и так была ошибка 
и нет подсказки джава по типу (msg: "show log error")

2022-07-07 19:41 UTC, mkarpenkoProvectus requested changes

2022-07-07 19:41 UTC, mkarpenkoProvectus commented on src/logger_enum/circleArea.java
> +            final Logger LOGGER = Logger.getLogger(circleArea.class.getName());
так тут же всё равно сторонний логгер подключен

2022-07-07 19:41 UTC, mkarpenkoProvectus commented on src/logger_enum/LoggerTest.java
> +        new LoggerCreator().showLoggerLevel(LoggerEnum.INFO);
основная задача логгера - вывести в лог(консоль) сообщение, а не только же уровень логирования :)

2022-07-18 17:21 UTC, apollyonix approved these changes

2022-07-18 17:23 UTC, merged